Vagrant.configure("2") do |config|
  config.vm.define :puppetserver do |node|
    puppetserver_ip       = '10.0.0.10'
    puppetserver_hostname = 'puppetserver.local'
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end
    node.vm.box              = "bento/centos-7.3"
    node.vm.box_check_update = false
    node.vm.synced_folder    ".", "/vagrant", disabled: true
    node.vm.hostname         = puppetserver_hostname
    node.vm.network :private_network, :ip => puppetserver_ip
    node.vm.network "forwarded_port", guest: 443, host: 1443
    node.vm.network "forwarded_port", guest: 8140, host: 18140

  end
end
