Vagrant.configure("2") do |config|
    puppetserver_ip       = '10.0.0.10'
    puppetserver_hostname = 'puppetserver.local'
    
  config.vm.define :puppetserver do |node|
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "4000"
	  vb.cpus = "2"
    end
    node.vm.box              = "bento/centos-7.3"
    node.vm.box_check_update = false
    node.vm.synced_folder    ".", "/vagrant", disabled: true
    node.vm.hostname         = puppetserver_hostname
    node.vm.network :private_network, :ip => puppetserver_ip
    node.vm.network "forwarded_port", guest: 443, host: 1443
    node.vm.network "forwarded_port", guest: 8140, host: 18140

  end
  config.vm.define :linuxagent do |node|
    ip       = '10.0.0.12'
    hostname = 'linuxagent'
    role='linux_webserver'
    environment='webdata'
    psk=''
    agent_install_cmd    = "curl -k https://#{puppetserver_hostname}:8140/packages/current/install.bash | sudo bash -s"
    agent_install_params = "custom_attributes:challengePassword=#{psk} extension_requests:pp_role=#{role} agent:environment=#{environment}" 

    node.vm.provider "virtualbox" do |vb|
      vb.memory = "2000"
	  vb.cpus = "2"
    end
    node.vm.box              = "bento/centos-7.3"
    node.vm.box_check_update = false
    node.vm.synced_folder    ".", "/vagrant", disabled: false
    node.vm.hostname         = hostname
    node.vm.network :private_network, :ip => ip
    node.vm.provision "shell", inline: "echo \'#{puppetserver_ip} #{puppetserver_hostname}\' > /etc/hosts"
    node.vm.provision "shell", inline: "#{agent_install_cmd} #{agent_install_params}"

  end
#  config.vm.define :windowsagent do |node|
#    ip       = '10.0.0.11'
#    hostname = 'windowsagent'
#    node.vm.provider "virtualbox" do |vb|
#      vb.memory = "4096"
#	  vb.cpus = "2"
#    end
#    node.vm.box              = "jacqinthebox/windowsserver2016"
#    node.vm.box_check_update = false
#    node.vm.synced_folder    ".", "/vagrant", disabled: true
#    node.vm.hostname         = hostname
#    node.vm.network :private_network, :ip => ip
#    node.vm.provision "shell",inline:"$p=\"C:\\Windows\\System32\\drivers\\etc\\hosts\";$hosts=gc $p;$new = $hosts + \"\`n#{puppetserver_ip} #{puppetserver_hostname}\";sc -path $p -value $new;gc $p"
#    node.vm.provision "shell",inline:"[Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}; $webClient = New-Object System.Net.WebClient; $webClient.DownloadFile(\'https://#{puppetserver_hostname}:8140/packages/current/install.ps1\', \'install.ps1\'); .\\install.ps1 custom_attributes:challengePassword=psk extension_requests:pp_role=webserver"
#  end
  
end
